CREATE TABLE veiculo
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa  VARCHAR(20) NOT NULL UNIQUE,
    marca  VARCHAR(50) NOT NULL,
    modelo VARCHAR(50) NOT NULL,
    ano    INT         NOT NULL
);

-- Seed the table with 10 initial records
-- 2. Insert seed data (10 vehicles)
INSERT INTO veiculo (placa, marca, modelo, ano)
VALUES
-- Old Brazilian format (Padrão Nacional: LLL-NNNN)
('ABC-1234', 'Fiat', 'Uno', 2010),
('DEF-5678', 'Volkswagen', 'Gol', 2014),
('GHI-9012', 'Chevrolet', 'Celta', 2012),
('JKL-3456', 'Ford', 'Ka', 2015),
('MNO-7890', 'Honda', 'Civic', 2018),

-- New Mercosul format (Padrão Mercosul: LLLNLNN)
('PQR1S23', 'Chevrolet', 'Onix', 2021),
('TUV4W56', 'Hyundai', 'HB20', 2022),
('XYZ7A89', 'Toyota', 'Corolla', 2023),
('BRA2E19', 'Jeep', 'Renegade', 2020),
('RIO3F45', 'Volkswagen', 'Polo', 2024);