CREATE TABLE cliente
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome             VARCHAR(100) NOT NULL,
    tipo_pessoa      VARCHAR(2)   NOT NULL CHECK (tipo_pessoa IN ('PF', 'PJ')),
    documento        VARCHAR(18)  NOT NULL UNIQUE,
    data_nascimento  DATE,
    email            VARCHAR(150)
);

-- Seed Data
INSERT INTO cliente (nome, tipo_pessoa, documento, data_nascimento, email)
VALUES

-- CPF
('Maria Silva',        'PF', '52998224725',   '1990-05-15', 'maria.silva@email.com'),
('João Oliveira',      'PF', '11144477735',   '1985-11-22', 'joao.oliveira@email.com'),
('Ana Costa',          'PF', '98765432100',   NULL,         NULL),

-- CNPJ numérico
('Tech Solutions',     'PJ', '11222333000181', NULL,        'contato@techsolutions.com'),
('Auto Peças Brasil',  'PJ', '12345678000195', NULL,        NULL),
('Oficina do Zé',      'PJ', '98765432000198', NULL,        NULL),

-- CNPJ alfanumérico
('Alpha Tech LTDA',    'PJ', '1A234B567C8964', NULL,        NULL),
('Beta Soluções S/A',  'PJ', 'ZA000BC100DE88', NULL,        NULL),
('Gamma Digital ME',   'PJ', 'AB123CD456EF80', NULL,        'gamma@digital.com');
