CREATE TABLE IF NOT EXISTS tipo_peca (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    valor_unitario DECIMAL(10, 2) NOT NULL,
    quantidade_estoque INTEGER NOT NULL
);

-- Seeds
INSERT INTO tipo_peca (nome, valor_unitario, quantidade_estoque) VALUES
    ('Pastilha Freio', 120.00, 25),
    ('Disco Freio', 350.00, 12),
    ('Filtro Óleo', 35.90, 40),
    ('Filtro Ar', 42.50, 32),
    ('Óleo Sintético', 39.90, 80),
    ('Vela Ignição', 29.90, 60),
    ('Correia Dentada', 210.00, 15),
    ('Amortecedor Front', 480.00, 10),
    ('Bateria 60Ah', 520.00, 8),
    ('Lâmpada Farol', 24.90, 50);
