CREATE TABLE IF NOT EXISTS tipo_servico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(500),
    valor DECIMAL(10, 2)
    );


-- seed de dados para tipo_servico
INSERT INTO tipo_servico (nome, valor) VALUES
    ('Troca de Óleo', 89.90),
    ('Alinhamento', 75.00),
    ('Balanceamento', 60.00),
    ('Revisão Completa', 350.00),
    ('Troca de Pneu', 45.00),
    ('Freios', 220.00),
    ('Suspensão', 180.00),
    ('Ar Condicionado', 150.00),
    ('Elétrica', 120.00),
    ('Funilaria e Pintura', 500.00);