CREATE TABLE IF NOT EXISTS ordem_de_servico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(25),
    solicitacao VARCHAR(500),
    orcamento DECIMAL(10, 2),
    id_cliente BIGINT,
    id_veiculo BIGINT,
    CONSTRAINT fk_os_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id),
    CONSTRAINT fk_os_veiculo FOREIGN KEY (id_veiculo) REFERENCES veiculo(id)
);
