CREATE TABLE IF NOT EXISTS servico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ordem_de_servico BIGINT NOT NULL,
    id_tipo_servico BIGINT NOT NULL,
    status VARCHAR(25),
    data_inicio TIMESTAMP,
    data_fim TIMESTAMP,
    FOREIGN KEY (id_tipo_servico) REFERENCES tipo_servico(id),
    FOREIGN KEY (id_ordem_de_servico) REFERENCES ordem_de_servico(id)
    );
