-- Tabela de usuários do sistema
CREATE TABLE oficina.usuario
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login       VARCHAR(100) NOT NULL UNIQUE,
    senha_hash  VARCHAR(255) NOT NULL,
    role        VARCHAR(20)  NOT NULL CHECK (role IN ('CLIENTE', 'MECANICO', 'ATENDENTE', 'GERENTE')),
    cliente_id  BIGINT REFERENCES oficina.cliente (id) ON DELETE SET NULL
);


-- Seed Data

-- Senha padrão: "senha@123" com hash
INSERT INTO oficina.usuario (login, senha_hash, role) VALUES
('gerente',   '$2a$10$PrHgO0KngM/X/f.NuNKXqeWAQlYFzhdqXbCaSk6ydcVaW3CtniFAS', 'GERENTE'),
('atendente', '$2a$10$PrHgO0KngM/X/f.NuNKXqeWAQlYFzhdqXbCaSk6ydcVaW3CtniFAS', 'ATENDENTE'),
('mecanico',  '$2a$10$PrHgO0KngM/X/f.NuNKXqeWAQlYFzhdqXbCaSk6ydcVaW3CtniFAS', 'MECANICO');

-- Usuário CLIENTE vinculado ao primeiro cliente do seed
INSERT INTO oficina.usuario (login, senha_hash, role, cliente_id)
SELECT '52998224725', '$2a$10$PrHgO0KngM/X/f.NuNKXqeWAQlYFzhdqXbCaSk6ydcVaW3CtniFAS', 'CLIENTE', id
FROM oficina.cliente
WHERE documento = '52998224725'
LIMIT 1;

