CREATE TABLE ordem_de_servico_status_historico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ordem_de_servico_id BIGINT NOT NULL REFERENCES ordem_de_servico(id),
    status VARCHAR(25) NOT NULL,
    changed_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_os_status_historico_ordem_changed_at
ON ordem_de_servico_status_historico (ordem_de_servico_id, changed_at DESC, id DESC);

INSERT INTO ordem_de_servico_status_historico (ordem_de_servico_id, status, changed_at)
SELECT id, status, data_hora_criacao AT TIME ZONE 'UTC'
FROM ordem_de_servico;
