apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: tech-challenge
data:
  DB_NAME: "oficina"
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_FLYWAY_ENABLED: "true"
  SPRING_FLYWAY_SCHEMAS: "oficina"
  SWAGGER_BASE_PATH: "/Prod"
